apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gatling
spec:
  params:
  - name: DURATION
    description: The duration of running simulations
    type: string
    default: "30"
  - name: CONCURRENT_USERS
    description: The number of concurrent users
    type: string
    default: "10"
  - name: APP_URL
    description: The application under test url
    type: string
  workspaces:
  - description: The workspace consisting of maven project.
    name: simulations      
  steps:
    - name: run-tests
      image: quay.io/siamaksade/gatling:latest
      env:
        - name: PIPELINERUN_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tekton.dev/pipelineRun']
      script: |
        #!/usr/bin/env bash

        # set simulation params
        export JAVA_OPTS="-DtestDuration=$(params.CONCURRENT_USERS) -DuserCount=$(params.DURATION) -Dserver=$(params.APP_URL)"

        # run simulation
        /opt/gatling/bin/gatling.sh -rd "PHP app Performance Test" -sf $(workspaces.simulations.path)
