apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: php-app-dev-init
spec:
  params:
    - default: cakephp
      name: APP_NAME
      type: string
    - default: cicd-tekton
      name: DEV_PROJ
      type: string
    - default: 'https://github.com/sandrotanaka/cakephp-ex.git'
      name: GIT_REPO
      type: string
    - default: ''
      name: GIT_REVISION
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/cicd-tekton/cakephp
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: 7.4-ubi8
      name: VERSION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-php
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: oc new-app --name=$(params.APP_NAME) $(params.APP_NAME)  -n $(params.DEV_PROJ)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: expose-service
      params:
        - name: SCRIPT
          value: oc expose svc $(params.APP_NAME) -n $(params.DEV_PROJ)
      runAfter:
        - deploy
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
      optional: false
