apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: php-app-dev-all
spec:
  params:
    - default: cakephp
      name: APP_NAME
      type: string
    - default: php-app-dev
      name: PROJ_DEV
      type: string
    - default: 'https://github.com/sandrotanaka/cakephp-ex.git'
      name: GIT_REPO
      type: string
    - default: ''
      name: GIT_REVISION
      type: string
    - default: image-registry.openshift-image-registry.svc:5000/php-app-dev/cakephp
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: 7.4-ubi8
      name: VERSION
      type: string
    - default: http://sonarqube-cicd-tekton.apps.cluster-vvj49.vvj49.sandbox1192.opentlc.com
      name: SONAR_HOST_URL
      type: string
    - default: cakephp
      name: SONAR_PROJECT_KEY
      type: string
    - default: .
      name: SONAR_SOURCES
      type: string
    - default: 23c464d342956edc3ed5d1eb20fc00b02ffecf74
      name: SONAR_LOGIN
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: sonarqube-scanner
      params:
        - name: SONAR_HOST_URL
          value: $(params.SONAR_HOST_URL)
        - name: SONAR_PROJECT_KEY
          value: $(params.SONAR_PROJECT_KEY)
        - name: PROJECT_VERSION
          value: '1.0'
        - name: SOURCE_TO_SCAN
          value: $(params.SONAR_SOURCES)
        - name: SONAR_SCANNER_IMAGE
          value: >-
            docker.io/sonarsource/sonar-scanner-cli:4.6@sha256:7a976330a8bad1beca6584c1c118e946e7a25fdc5b664d5c0a869a6577d81b4f
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source
          workspace: workspace
        - name: sonar-settings
          workspace: sonar-settings
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - sonarqube-scanner
      taskRef:
        kind: ClusterTask
        name: s2i-php
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout status deploy/$(params.APP_NAME) -n $(params.PROJ_DEV)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
    - name: sonar-settings
